name: Prudential MLOps CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This job runs basic checks on our code to ensure quality
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run basic import tests
        run: |
          python -c "import src.main; print('API script is importable.')"
          python -c "import src.train; print('Training script is importable.')"

  # This job handles retraining and deployment, and is triggered manually
  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    
    # We only run this job if it's triggered manually
    if: github.event_name == 'workflow_dispatch'

    # Add services that the job needs, like Redis for the Feast online store
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC
        uses: iterative/setup-dvc@v1
      
      # In a real project, you would configure DVC remote (e.g., S3) and AWS secrets
      # For now, this step confirms DVC is installed.
      - name: Verify DVC
        run: dvc --version

      - name: Apply Feature Store Definitions
        # Before training, we must apply our feature definitions
        run: |
          cd feature_repo
          feast apply
        
      - name: Run Model Training
        # We need to set up MLflow and connect to our Redis service
        env:
          # This tells Feast where to find the Redis service container
          FEAST_REDIS_HOST: localhost
        run: |
          # Start MLflow in the background
          mlflow server --host 127.0.0.1 --port 5000 &
          # Give it a moment to start
          sleep 5
          # Run the training script
          python src/train.py
          
      - name: Log in to Docker Hub
        # This uses secrets to securely log in to your container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        # This step builds the Dockerfile and pushes it to Docker Hub
        run: |
          # The image tag uses the GitHub SHA to be unique
          IMAGE_TAG=${{ github.sha }}
          # The repository name uses your Docker Hub username
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/prudential-api

          echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
          docker build . -t $IMAGE_NAME:$IMAGE_TAG

          echo "Pushing Docker image to Docker Hub..."
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "Image pushed successfully."

